name: Continous Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.email "felipe-cd@my-app.com"
          git config --global user.name "felipe-cd"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy gh-pages
        run: npm run deploy -- -r git@github.com:FelipePepe/Master8_Cloud_Ejercicio_2.git
